const eventsLocal = [{
  title: 'ELLE PART DANS DES TRUCS',
  leadText: 'Claire-Marie se raconte, se disperse et s\'égare pour notre plus grand bonheur. Un spectacle qui fait du bien !',
  coverUrl: 'https://cdn.paris.fr/qfap/2020/08/18/72516_VmlzdWVsIHBhcmlzZnIgZWxsZSBwYXJ0IGRhbnMgZGVzIHRydWNzLmpwZw==.jpg',
  tags: 'Ados;En famille;C\'est un peu;A chier;On va pas;Se mentir',
  priceType: 'payant',
  addressCity: 'Paris',
  id: '109066',
}, {
  title: 'ELLE PART DANS DES TRUCS',
  leadText: 'Claire-Marie se raconte, se disperse et s\'égare pour notre plus grand bonheur. Un spectacle qui fait du bien !',
  coverUrl: 'https://cdn.paris.fr/qfap/2020/08/18/72516_VmlzdWVsIHBhcmlzZnIgZWxsZSBwYXJ0IGRhbnMgZGVzIHRydWNzLmpwZw==.jpg',
  tags: 'Ados;En famille',
  priceType: 'payant',
  addressCity: 'Paris',
  id: '109066',
}, {
  title: 'ELLE PART DANS DES TRUCS',
  leadText: 'Claire-Marie se raconte, se disperse et s\'égare pour notre plus grand bonheur. Un spectacle qui fait du bien !',
  coverUrl: 'https://cdn.paris.fr/qfap/2020/08/18/72516_VmlzdWVsIHBhcmlzZnIgZWxsZSBwYXJ0IGRhbnMgZGVzIHRydWNzLmpwZw==.jpg',
  tags: 'Ados;En famille',
  priceType: 'payant',
  addressCity: 'Paris',
  id: '109066',
}, {
  title: 'ELLE PART DANS DES TRUCS',
  leadText: 'Claire-Marie se raconte, se disperse et s\'égare pour notre plus grand bonheur. Un spectacle qui fait du bien !',
  coverUrl: 'https://cdn.paris.fr/qfap/2020/08/18/72516_VmlzdWVsIHBhcmlzZnIgZWxsZSBwYXJ0IGRhbnMgZGVzIHRydWNzLmpwZw==.jpg',
  tags: 'Ados;En famille',
  priceType: 'payant',
  addressCity: 'Paris',
  id: '109066',
}, {
  title: 'ELLE PART DANS DES TRUCS',
  leadText: 'Claire-Marie se raconte, se disperse et s\'égare pour notre plus grand bonheur. Un spectacle qui fait du bien !',
  coverUrl: 'https://cdn.paris.fr/qfap/2020/08/18/72516_VmlzdWVsIHBhcmlzZnIgZWxsZSBwYXJ0IGRhbnMgZGVzIHRydWNzLmpwZw==.jpg',
  tags: 'Ados;En famille',
  priceType: 'payant',
  addressCity: 'Paris',
  id: '109066',
}, {
  title: 'ELLE PART DANS DES TRUCS',
  leadText: 'Claire-Marie se raconte, se disperse et s\'égare pour notre plus grand bonheur. Un spectacle qui fait du bien !',
  coverUrl: 'https://cdn.paris.fr/qfap/2020/08/18/72516_VmlzdWVsIHBhcmlzZnIgZWxsZSBwYXJ0IGRhbnMgZGVzIHRydWNzLmpwZw==.jpg',
  tags: 'Ados;En famille;C\'est un peu;A chier;On va pas;Se mentir',
  priceType: 'payant',
  addressCity: 'Paris',
  id: '109066',
}];

export default eventsLocal;
